version: '3.8'

services:
  

  backend:
    build:
      context: ./backend
    container_name: job_scheduler_backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/job_scheduler
      NODE_ENV: development
      LLM_SERVICE_URL: http://host.docker.internal:8000 # LLMサービスのURL (ホストマシン上のサービス)
    networks:
      - app_network

  db:
    image: postgres:14
    container_name: job_scheduler_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  

networks:
  app_network:


volumes:
  postgres_data:
