receivers:
  otlp:
    protocols:
      grpc:
      http:
  jaeger:
    protocols:
      thrift_compact:

exporters:
  logging:
    loglevel: debug
  otlphttp/phoenix:
    endpoint: "http://phoenix:6006"
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp, jaeger]
      exporters: [logging, otlphttp/phoenix]
    metrics:
      receivers: [otlp]
      exporters: [logging, otlphttp/phoenix]
    logs:
      receivers: [otlp]
      exporters: [logging, otlphttp/phoenix]